### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'publish' when sending SNS message

### ISSUE THREAD

**Issue by stardothosting** [evannuil/aws-snapshot-tool#7]
I got the following trackback error when the script tries to send an SNS message :+1: 

Traceback (most recent call last):
  File "./makesnapshots.py", line 181, in <module>
    sns.publish(mytopic_arn,message,"Finished AWS snapshotting")
AttributeError: 'NoneType' object has no attribute 'publish'

This was resolved by putting the following line right before the script sends messages :

sns = boto.connect_sns()

**Comment by Omar-Khawaja** [comment]
I came across this same error, but I'm not able to resolve it. I made sure my region is correct. I'm using "us-east-2" as my region. Did you have to format the region a special way?
